language: cpp

install:
    - cmake --version

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

matrix:
    fast_finish: true
    allow_failures:
        - os: osx

env:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

before_script:
    - if [ "$CC" = "gcc" ]; then
    -   export CC=gcc-4.9;
    -   export CXX=g++-4.9;
    - fi

script:
    - mkdir build && cd build
    - cmake -G "Ninja" ..
    - cmake --build . --clean-first

after_success:
    - ctest

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - cmake
            - cmake-data
            - gcc-4.9
            - g++-4.9
            - ninja-build
