language: cpp
compiler: gcc

install:
    - cmake --version

os:
    - linux
    - osx

matrix:
    fast_finish: true
    allow_failures:
        - os: osx

env:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

script:
    - mkdir build && cd build
    - CC=gcc-4.9 CXX=g++-4.9 cmake ..
    - cmake --build . --clean-first
    - ctest

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - cmake
            - cmake-data
            - gcc-4.9
            - g++-4.9
