version: 1.0.{build}-{branch}

branches:
    except:
        - gh-pages

skip_tags: true

environment:
    matrix:
        - CMAKE_BUILD_TYPE: Debug
        - CMAKE_BUILD_TYPE: Release
        - CMAKE_BUILD_TYPE: Debug
          CMAKE_GENERATOR: -G "MinGW Makefiles"
        - CMAKE_BUILD_TYPE: Release
          CMAKE_GENERATOR: -G "MinGW Makefiles"

before_build:
    - git submodule init
    - git submodule update

build_script:
    - mkdir build && cd build
    - cmake ${CMAKE_GENERATOR} ..
    - cmake --build . --clean-first

test_script:
    - ctest

